Add Output JSON code sample from Docs API
googleworkspace/browser-samples pull request #46
Opened 2019-08-12 03:09 UTC by asrivas

Please see: https://devsite.googleplex.com/docs/api/samples/output-json

2019-08-12 16:03 UTC, erickoledadevrel requested changes

2019-08-12 16:03 UTC, erickoledadevrel commented on docs/outputJSON/index.html
> +      // Handle the initial sign-in state.
Indent is wrong.

2019-08-12 16:03 UTC, erickoledadevrel commented on docs/outputJSON/index.html
> +        apiKey: API_KEY,
Indent is wrong.

2019-08-12 16:03 UTC, erickoledadevrel commented on docs/outputJSON/index.html
> +        authorizeButton.style.display = 'none';
More indent issues.

2019-08-12 16:03 UTC, erickoledadevrel commented on docs/outputJSON/index.html
> +        documentId: 'DOCUMENT_ID'
Ditto

2019-08-12 16:03 UTC, erickoledadevrel commented
Also fix lint errors.

2020-07-06 06:28 UTC, qiliiiliiiiliiiliq commented
Delete ssh please

2025-11-19 04:17 UTC, closed without merging